source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'DajieVPN' do
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
  pod 'UMengSocial'
  pod 'UMengAnalytics'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SDWebImage'
  pod 'BlocksKit'
end
